Repository ONTechNITS/RapidHTML, pull requests merged in 2024-08, with the labels that each got.

#23 Add self closing html tag support
  pyproject.toml
  src/quickhtml/tags.py
Labels: enhancement

#31 Add ability to pass custom user defined CSS
  .github/workflows/check_tests.yml
  Makefile
  src/rapidhtml/style/__init__.py
  src/rapidhtml/style/css.py
  src/rapidhtml/tags.py
  tests/test_css_style.py
Labels: new feature

#37 Added an example project deployable by end user
  examples/modern_table/README.md
  examples/modern_table/app.py
  examples/modern_table/data.json
  examples/modern_table/pyproject.toml
  examples/modern_table/styles.py
  examples/modern_table/table_html.py
Labels: documentation

#40 Adding in missing H tags
  src/rapidhtml/tags.py
Labels: bug

#42 Add issue and PR templates and CODEOWNERS
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, enhancement

#30 QuickHTMLCallback dataclass
  docs/examples.rst
  docs/examples/tag_callbacks.rst
  src/rapidhtml/callbacks.py
  src/rapidhtml/tags.py
  tests/test_tags.py
Labels: enhancement

#47 Added ability to select and pop tags. Added functionality to auto-merge Head tags if multiple present
  .gitignore
  src/rapidhtml/routing.py
  src/rapidhtml/style/css.py
  src/rapidhtml/tags.py
  tests/test_tags.py
  tests/test_tags_select.py
Labels: enhancement, new feature

#41 Added default favicon and title
  src/rapidhtml/app.py
  src/rapidhtml/static/RapidHTML.svg
  src/rapidhtml/utils/__init__.py
  tests/test_app.py
Labels: enhancement

#45 Went way too far with the type hinting...
  README.md
  src/rapidhtml/bases.py
  src/rapidhtml/style/css.py
  src/rapidhtml/tags.py
  src/rapidhtml/utils/__init__.py
  tests/test_tags.py
Labels: documentation, enhancement
